spring:
  profiles:
    active: "local"
---
spring:
  datasource:
    url: "jdbc:log4jdbc:mysql://192.168.56.1:3310/workspace?verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC"
    username: "root"
    password: "!@#QWEasd123"
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
server:
  port: 8888
---
spring:
  # YAML
  messages:
    basename: messages
    encoding: UTF-8
  # Encoding
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
#server
server:
  error:
    whitelabel:
      enabled: false
  # Redis / Session
  servlet:
    session:
      timeout: "30m"
# Logging
logging:
  level:
    jdbc.sqlonly: OFF
    jdbc.sqltiming: DEBUG
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: OFF
    jdbc.connection: OFF
    org.hibernate: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
      springframework:
        web: debug
        security: debug
---
spring:
  thymeleaf:
    cache: false
  devtools:
    remote:
      restart:
        enabled: true
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  session:
    store-type: none
---
mybatis:
  config-location: classpath:mybatis-configuration.xml
  mapper-locations: classpath:mappers/**.xml