spring:
  profiles:
    active: "local"
---
spring:
  datasource:
    url: "jdbc:log4jdbc:mysql://localhost:3306/workspace?verifyServerCertificate=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC"
    username: "root"
    password: "root"
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
server:
  port: 8888
---
spring:
  thymeleaf:
    cache: false
  devtools:
    remote:
      restart:
        enabled: true
---
mybatis:
  config-location: classpath:mybatis-configuration.xml
  mapper-locations: classpath:mappers/**.xml